osx_image: xcode10
language: swift
sudo: true
env:
  global:
    - EXPANDED_CODE_SIGN_IDENTITY="-"
    - EXPANDED_CODE_SIGN_IDENTITY_NAME="-"
    - EXPANDED_PROVISIONING_PROFILE="-"
before_script:
- sh Scripts/git_auth.sh
script:
- travis_retry Scripts/ci.sh
- sleep 3